<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<!--

(C) Copyright 2012 Linden Research, Inc.
(C) Copyright 2013-2016 Sei Lisa.
Sei Lisa is the username of one of the authors in the Second Life online
virtual world.

    LSL2 Keywords Database

    LSL2 Keywords Database is free software: you can redistribute it
    and/or modify it under the terms of the GNU Lesser General Public License
    as published by the Free Software Foundation, either version 3 of the
    License, or (at your option) any later version.

    LSL2 Keywords Database is distributed in the hope that it will be
    useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
    GNU Lesser General Public License for more details.

    You should have received a copy of the GNU Lesser General Public License
    along with LSL2 Keywords Database. If not, see
    <http://www.gnu.org/licenses/>.

Second Life is a trademark of Linden Research, Inc.

-->

<!--

Currently supported grids (LSL dialects):
sl - Second Life
os - OpenSim
aa - AuroraSim

The grid= attribute can be omitted, meaning all supported grids.
If included, it should be a list of space-separated supported grids.
Example: grid="os aa"

-->

<!-- DOCTYPE keywords SYSTEM "kwdb.dtd" -->
<!-- Declare the DTD here to avoid problems with the Python parser we use -->

<!DOCTYPE keywords [

<!ELEMENT keywords (grid*, (keyword | type | constant | function | event)*,
                    (defaults, (keyword | type | constant | function | event)*)?)>
<!ATTLIST keywords
          version CDATA #REQUIRED>
<!ELEMENT grid (#PCDATA)>
<!ATTLIST grid
          id NMTOKEN #REQUIRED
          version CDATA #IMPLIED
          >
<!ELEMENT defaults (description*)>
<!ELEMENT keyword (description*)>
<!ATTLIST keyword
          name CDATA #REQUIRED
          grid NMTOKENS #IMPLIED
          status (normal | unimplemented) "normal">
<!ELEMENT type (description*)>
<!ATTLIST type
          name ID #REQUIRED
          grid NMTOKENS #IMPLIED>
<!ELEMENT constant (description*)>
<!ATTLIST constant
          name CDATA #REQUIRED
          grid NMTOKENS #IMPLIED
          type IDREF #REQUIRED
          value CDATA #IMPLIED
          version CDATA #IMPLIED
          status (normal | deprecated | unimplemented) "normal">
<!ELEMENT function (param | description)*>
<!ATTLIST function
          name CDATA #REQUIRED
          grid NMTOKENS #IMPLIED
          type IDREF #IMPLIED
          delay CDATA "0."
          energy CDATA "10."
          version CDATA #IMPLIED
          status (normal | deprecated | godmode | unimplemented) "normal">
<!ELEMENT event (param | description)*>
<!ATTLIST event
          name CDATA #REQUIRED
          version CDATA #IMPLIED
          grid NMTOKENS #IMPLIED>
<!ELEMENT description (#PCDATA)>
<!ATTLIST description
          lang NMTOKENS #REQUIRED>
<!ELEMENT param EMPTY>
<!ATTLIST param
          name CDATA #REQUIRED
          type IDREF #REQUIRED>

]>

<keywords version="0.0.20160606000">
  <!--The OpenSim/Aurora functions, constants and types are based on the following revisions:

      OpenSim revision 0.7.5-rc1
          http://dist.opensimulator.org/opensim-0.7.5-rc1-source.tar.gz

      AuroraSim revision 0049c9335f8b91ab119ce4fee5ba1d50d4f6f017
          https://github.com/aurora-sim/Aurora-Sim/commit/0049c9335f8b91ab119ce4fee5ba1d50d4f6f017
  -->

  <!-- Grids supported and their versions -->
  <grid id="sl" version="16.05.24.315768">Second Life</grid>
  <grid id="os" version="v0.7.5-rc1">OpenSimulator</grid>
  <grid id="aa" version="0049c9335f8b91ab119ce4fee5ba1d50d4f6f017">Aurora-Sim</grid>

  <!-- Defaults for absent descriptions -->
  <defaults>
    <description lang="en">
(No Description)
    </description>
  </defaults>

  <!-- Language keywords -->

  <keyword name="default">
    <description lang="en">
Name of default state that all scripts must have
    </description>
  </keyword>

  <keyword name="state">
    <description lang="en">
Keyword to indicate state block or state transition
    </description>
  </keyword>

  <keyword name="event" status="unimplemented" grid="sl"/>

  <keyword name="jump">
    <description lang="en">
jump statement
jump label;

    </description>
  </keyword>

  <keyword name="return">
    <description lang="en">
Leave current function or event handler
    </description>
  </keyword>

  <keyword name="if">
    <description lang="en">
if statement
if (test)
{    statements
}
    </description>
  </keyword>

  <keyword name="else">
    <description lang="en">
else clause
if (test)
{    statements
}
else
{    statements
}
    </description>
  </keyword>

  <keyword name="for">
    <description lang="en">
for loop
for (initializer; test; iteration)
{
   statements
}
    </description>
  </keyword>

  <keyword name="do">
    <description lang="en">
do loop
do
{
   statements
} while (test);
    </description>
  </keyword>

  <keyword name="while">
    <description lang="en">
while loop
while (test)
{    statements
}
    </description>
  </keyword>

  <keyword name="print" grid="sl"/>


  <!-- Language types -->

  <type name="integer">
    <description lang="en">
Integer type
    </description>
  </type>

  <type name="float">
    <description lang="en">
Floating-point type
    </description>
  </type>

  <type name="string">
    <description lang="en">
String type
    </description>
  </type>

  <type name="key">
    <description lang="en">
Key type. Use NULL_KEY to test for empty keys.
    </description>
  </type>

  <type name="vector">
    <description lang="en">
Vector type of 3 floats. Used to represent 3D motion, Euler angles, and color.
Access components by .x, .y, or .z
    </description>
  </type>

  <type name="rotation">
    <description lang="en">
Rotation type of 4 floats. Used to represent rotation.
Access components by .x, .y, .z, or .s
    </description>
  </type>

  <type name="quaternion">
    <description lang="en">
Rotation type of 4 floats. Used to represent rotation.
Access components by .x, .y, .z, or .s
    </description>
  </type>

  <type name="list">
    <description lang="en">
List of various data types
    </description>
  </type>

  <type name="bool" grid="os aa">
    <description lang="en">
Boolean type, either TRUE or FALSE
    </description>
  </type>

<!-- Not included:
  <type name="DateTime" grid="aa">
    <description lang="en">
Type for a date and time value
    </description>
  </type>
-->


  <!-- Language constants

       In LSL, TRUE and FALSE are actually keywords, not constants.
       The main difference between TRUE/FALSE and a constant is that
       you can write in globals: integer j = -CONSTANT;
       but you can't write: integer j = -TRUE; or -FALSE
       (although it is allowed in local definitions).

       However, the subtle difference doesn't justify them
       being treated as anything but constants. After all,
       internally, LSL constants are keywords too.
  -->

  <constant name="TRUE" type="integer" value="1">
    <description lang="en">
Integer constant for Boolean operations
    </description>
  </constant>

  <constant name="FALSE" type="integer" value="0">
    <description lang="en">
Integer constant for Boolean operations
    </description>
  </constant>

  <constant name="STATUS_PHYSICS" type="integer" value="0x1">
    <description lang="en">
Passed in the llSetStatus library function. If TRUE, object moves physically.
    </description>
  </constant>

  <constant name="STATUS_PHANTOM" type="integer" value="0x10">
    <description lang="en">
Passed in the llSetStatus library function. If TRUE, object doesn't collide with other objects.
    </description>
  </constant>

  <constant name="STATUS_ROTATE_X" type="integer" value="0x2">
    <description lang="en">
Passed in the llSetStatus library function. If FALSE, object doesn't rotate around local X axis.
    </description>
  </constant>

  <constant name="STATUS_ROTATE_Y" type="integer" value="0x4">
    <description lang="en">
Passed in the llSetStatus library function. If FALSE, object doesn't rotate around local Y axis.
    </description>
  </constant>

  <constant name="STATUS_ROTATE_Z" type="integer" value="0x8">
    <description lang="en">
Passed in the llSetStatus library function. If FALSE, object doesn't rotate around local Z axis.
    </description>
  </constant>

  <constant name="STATUS_SANDBOX" type="integer" value="0x20">
    <description lang="en">
Passed in the llSetStatus library function. If TRUE, object can't cross region boundaries or move more than 10 meters from its start location.
    </description>
  </constant>

  <constant name="STATUS_BLOCK_GRAB" type="integer" value="0x40" version="sl:0.2.0">
    <description lang="en">
Passed in the llSetStatus library function. If TRUE, object can't be grabbed and physically dragged.
    </description>
  </constant>

  <constant name="STATUS_BLOCK_GRAB_OBJECT" type="integer" value="0x400" grid="sl aa">
    <description lang="en">
Passed in the llSetStatus library function. If TRUE, the object can't be moved by grabs.
This flag applies to the entire linkset.
    </description>
  </constant>

  <constant name="STATUS_DIE_AT_EDGE" type="integer" value="0x80" version="sl:0.2.0">
    <description lang="en">
Passed in the llSetStatus library function. If TRUE, objects that reach the edge of the world just die
rather than teleporting back to the owner.
    </description>
  </constant>

  <constant name="STATUS_RETURN_AT_EDGE" type="integer" value="0x100" version="sl:1.5.0">
    <description lang="en">
Passed in the llSetStatus library function. If TRUE, script rezzed objects that reach the edge of the world are returned rather than killed.
STATUS_RETURN_AT_EDGE trumps STATUS_DIE_AT_EDGE if both are set.
    </description>
  </constant>

  <constant name="STATUS_CAST_SHADOWS" type="integer" value="0x200">
    <description lang="en">
Passed in the llSetStatus library function. If TRUE, object casts shadows on other objects.
    </description>
  </constant>

  <constant name="AGENT" type="integer" value="0x1">
    <description lang="en">
Passed in llSensor library function to look for other Agents (by Legacy name if filtered)
    </description>
  </constant>

  <constant name="AGENT_BY_USERNAME" type="integer" value="0x10">
    <description lang="en">
Passed in llSensor library function to look for other Agents, filtering by username
    </description>
  </constant>

  <constant name="AGENT_BY_LEGACY_NAME" type="integer" value="0x1">
    <description lang="en">
Passed in llSensor library function to look for other Agents, filtering by legacy name
    </description>
  </constant>

  <constant name="ACTIVE" type="integer" value="0x2">
    <description lang="en">
Passed in llSensor library function to look for moving objects
    </description>
  </constant>

  <constant name="PASSIVE" type="integer" value="0x4">
    <description lang="en">
Passed in llSensor library function to look for objects that aren't moving
    </description>
  </constant>

  <constant name="SCRIPTED" type="integer" value="0x8">
    <description lang="en">
Passed in llSensor library function to look for scripted objects
    </description>
  </constant>

  <constant name="CONTROL_FWD" type="integer" value="0x1">
    <description lang="en">
Passed to llTakeControls library function and used control event handler to test for agent forward control
    </description>
  </constant>

  <constant name="CONTROL_BACK" type="integer" value="0x2">
    <description lang="en">
Passed to llTakeControls library function and used control event handler to test for agent back control
    </description>
  </constant>

  <constant name="CONTROL_LEFT" type="integer" value="0x4">
    <description lang="en">
Passed to llTakeControls library function and used control event handler to test for agent left control
    </description>
  </constant>

  <constant name="CONTROL_RIGHT" type="integer" value="0x8">
    <description lang="en">
Passed to llTakeControls library function and used control event handler to test for agent right control
    </description>
  </constant>

  <constant name="CONTROL_ROT_LEFT" type="integer" value="0x100">
    <description lang="en">
Passed to llTakeControls library function and used control event handler to test for agent rotate left control
    </description>
  </constant>

  <constant name="CONTROL_ROT_RIGHT" type="integer" value="0x200">
    <description lang="en">
Passed to llTakeControls library function and used control event handler to test for agent rotate right control
    </description>
  </constant>

  <constant name="CONTROL_UP" type="integer" value="0x10">
    <description lang="en">
Passed to llTakeControls library function and used control event handler to test for agent up control
    </description>
  </constant>

  <constant name="CONTROL_DOWN" type="integer" value="0x20">
    <description lang="en">
Passed to llTakeControls library function and used control event handler to test for agent down control
    </description>
  </constant>

  <constant name="CONTROL_LBUTTON" type="integer" value="0x10000000">
    <description lang="en">
Passed to llTakeControls library function and used control event handler to test for agent left button control
    </description>
  </constant>

  <constant name="CONTROL_ML_LBUTTON" type="integer" value="0x40000000">
    <description lang="en">
Passed to llTakeControls library function and used control event handler to test for agent left button control with the agent in mouse look
    </description>
  </constant>

  <constant name="PERMISSION_DEBIT" type="integer" value="0x2">
    <description lang="en">
Passed to llRequestPermissions library function to request permission to take L$ from agent's account
    </description>
  </constant>

  <constant name="PERMISSION_TAKE_CONTROLS" type="integer" value="0x4">
    <description lang="en">
Passed to llRequestPermissions library function to request permission to take agent's controls
    </description>
  </constant>

  <constant name="PERMISSION_REMAP_CONTROLS" type="integer" value="0x8" status="unimplemented">
    <description lang="en">
<!-- TODO: add documentation -->
    </description>
  </constant>

  <constant name="PERMISSION_TRIGGER_ANIMATION" type="integer" value="0x10">
    <description lang="en">
Passed to llRequestPermissions library function to request permission to trigger animation on agent
    </description>
  </constant>

  <constant name="PERMISSION_ATTACH" type="integer" value="0x20">
    <description lang="en">
Passed to llRequestPermissions library function to request permission to attach/detach from agent
    </description>
  </constant>

  <constant name="PERMISSION_RELEASE_OWNERSHIP" type="integer" value="0x40" status="unimplemented">
    <description lang="en">
<!-- TODO: add documentation -->
    </description>
  </constant>

  <constant name="PERMISSION_CHANGE_LINKS" type="integer" value="0x80">
    <description lang="en">
Passed to llRequestPermissions library function to request permission to change links
    </description>
  </constant>

  <constant name="PERMISSION_CHANGE_JOINTS" type="integer" value="0x100" status="unimplemented">
    <description lang="en">
<!-- TODO: add documentation -->
    </description>
  </constant>

  <constant name="PERMISSION_CHANGE_PERMISSIONS" type="integer" value="0x200" status="unimplemented">
    <description lang="en">
<!-- TODO: add documentation -->
    </description>
  </constant>

  <constant name="PERMISSION_TRACK_CAMERA" type="integer" value="0x400">
    <description lang="en">
Passed to llRequestPermissions library function to request permission to track agent's camera
    </description>
  </constant>

  <constant name="PERMISSION_CONTROL_CAMERA" type="integer" value="0x800" version="sl:1.9.0(15)">
    <description lang="en">
Passed to llRequestPermissions library function to request permission to change agent's camera
    </description>
  </constant>

  <constant name="PERMISSION_TELEPORT" type="integer" value="0x1000" grid="sl aa">
    <description lang="en">
Passed to llRequestPermissions library function to request permission to teleport an agent
    </description>
  </constant>

  <constant name="PERMISSION_SILENT_ESTATE_MANAGEMENT" type="integer" value="0x4000" grid="sl">
    <description lang="en">
<!-- TODO: add documentation -->
    </description>
  </constant>

  <constant name="PERMISSION_OVERRIDE_ANIMATIONS" type="integer" value="0x8000" grid="sl">
    <description lang="en">
Passed to llRequestPermissions library function to request permission to override animations
    </description>
  </constant>

  <constant name="PERMISSION_RETURN_OBJECTS" type="integer" value="0x10000" grid="sl">
    <description lang="en">
<!-- TODO: add documentation -->
    </description>
  </constant>

  <constant name="PERMISSION_COMBAT" type="integer" value="0x2004" grid="aa">
    <description lang="en">
<!-- TODO: add documentation -->
    </description>
  </constant>


  <constant name="DEBUG_CHANNEL" type="integer" value="0x7FFFFFFF" version="sl:1.9.0(15)">
    <description lang="en">
Chat channel reserved for debug and error messages from scripts
    </description>
  </constant>

  <constant name="PUBLIC_CHANNEL" type="integer" value="0">
    <description lang="en">
Chat channel that broadcasts to all nearby users
    </description>
  </constant>

  <constant name="AGENT_FLYING" type="integer" value="0x1" version="sl:0.4.0">
    <description lang="en">
Returned by llGetAgentInfo if the Agent is flying
    </description>
  </constant>

  <constant name="AGENT_ATTACHMENTS" type="integer" value="0x2" version="sl:0.4.0">
    <description lang="en">
Returned by llGetAgentInfo if the Agent has attachments
    </description>
  </constant>

  <constant name="AGENT_SCRIPTED" type="integer" value="0x4" version="sl:0.4.0">
    <description lang="en">
Returned by llGetAgentInfo if the Agent has scripted attachments
    </description>
  </constant>

  <constant name="AGENT_SITTING" type="integer" value="0x10">
    <description lang="en">
Returned by llGetAgentInfo if the Agent is sitting
    </description>
  </constant>

  <constant name="AGENT_ON_OBJECT" type="integer" value="0x20">
    <description lang="en">
Returned by llGetAgentInfo if the Agent is sitting on an object
    </description>
  </constant>

  <constant name="AGENT_MOUSELOOK" type="integer" value="0x8">
    <description lang="en">
Returned by llGetAgentInfo if the Agent is in mouselook
    </description>
  </constant>

  <constant name="AGENT_AWAY" type="integer" value="0x40">
    <description lang="en">
Returned by llGetAgentInfo if the Agent is in away mode
    </description>
  </constant>

  <constant name="AGENT_WALKING" type="integer" value="0x80">
    <description lang="en">
Returned by llGetAgentInfo if the Agent is walking
    </description>
  </constant>

  <constant name="AGENT_IN_AIR" type="integer" value="0x100">
    <description lang="en">
Returned by llGetAgentInfo if the Agent is in the air
    </description>
  </constant>

  <constant name="AGENT_TYPING" type="integer" value="0x200">
    <description lang="en">
Returned by llGetAgentInfo if the Agent is typing
    </description>
  </constant>

  <constant name="AGENT_CROUCHING" type="integer" value="0x400">
    <description lang="en">
Returned by llGetAgentInfo if the Agent is crouching
    </description>
  </constant>

  <constant name="AGENT_BUSY" type="integer" value="0x800">
    <description lang="en">
Returned by llGetAgentInfo if the Agent is busy
    </description>
  </constant>

  <constant name="AGENT_ALWAYS_RUN" type="integer" value="0x1000">
    <description lang="en">
Returned by llGetAgentInfo if the Agent has 'Always Run' enabled
    </description>
  </constant>

  <constant name="AGENT_AUTOPILOT" type="integer" value="0x2000" grid="sl">
    <description lang="en">
Returned by llGetAgentInfo if the Agent is under autopilot control
    </description>
  </constant>

  <constant name="AGENT_LIST_PARCEL" type="integer" value="1">
    <description lang="en">
Passed to llGetAgentList to return only agents on the same parcel where the script is running
    </description>
  </constant>

  <constant name="AGENT_LIST_PARCEL_OWNER" type="integer" value="2">
    <description lang="en">
Passed to llGetAgentList to return only agents on any parcel in the region where the parcel owner is the same as the owner of the parcel under the scripted object
    </description>
  </constant>

  <constant name="AGENT_LIST_REGION" type="integer" value="4">
    <description lang="en">
Passed to llGetAgentList to return any/all agents in the region
    </description>
  </constant>

  <constant name="PSYS_PART_FLAGS" type="integer" value="0"/>
  <constant name="PSYS_PART_START_COLOR" type="integer" value="1"/>
  <constant name="PSYS_PART_START_ALPHA" type="integer" value="2"/>
  <constant name="PSYS_PART_START_SCALE" type="integer" value="5"/>
  <constant name="PSYS_PART_END_COLOR" type="integer" value="3"/>
  <constant name="PSYS_PART_END_ALPHA" type="integer" value="4"/>
  <constant name="PSYS_PART_END_SCALE" type="integer" value="6"/>
  <constant name="PSYS_PART_MAX_AGE" type="integer" value="7"/>
  <constant name="PSYS_PART_INTERP_COLOR_MASK" type="integer" value="0x1"/>
  <constant name="PSYS_PART_INTERP_SCALE_MASK" type="integer" value="0x2"/>
  <constant name="PSYS_PART_BOUNCE_MASK" type="integer" value="0x4"/>
  <constant name="PSYS_PART_WIND_MASK" type="integer" value="0x8"/>
  <constant name="PSYS_PART_FOLLOW_SRC_MASK" type="integer" value="0x10"/>
  <constant name="PSYS_PART_FOLLOW_VELOCITY_MASK" type="integer" value="0x20"/>
  <constant name="PSYS_PART_TARGET_POS_MASK" type="integer" value="0x40"/>
  <constant name="PSYS_PART_TARGET_LINEAR_MASK" type="integer" value="0x80"/>
  <constant name="PSYS_PART_EMISSIVE_MASK" type="integer" value="0x100"/>
  <constant name="PSYS_PART_RIBBON_MASK" type="integer" value="0x400" grid="sl"/>
  <constant name="PSYS_SRC_PATTERN" type="integer" value="9"/>
  <constant name="PSYS_PART_BF_ONE" type="integer" value="0" grid="sl"/>
  <constant name="PSYS_PART_BF_ZERO" type="integer" value="1" grid="sl"/>
  <constant name="PSYS_PART_BF_DEST_COLOR" type="integer" value="2" grid="sl"/>
  <constant name="PSYS_PART_BF_SOURCE_COLOR" type="integer" value="3" grid="sl"/>
  <constant name="PSYS_PART_BF_ONE_MINUS_DEST_COLOR" type="integer" value="4" grid="sl"/>
  <constant name="PSYS_PART_BF_ONE_MINUS_SOURCE_COLOR" type="integer" value="5" grid="sl"/>
  <constant name="PSYS_PART_BF_SOURCE_ALPHA" type="integer" value="7" grid="sl"/>
  <constant name="PSYS_PART_BF_ONE_MINUS_SOURCE_ALPHA" type="integer" value="9" grid="sl"/>

  <constant name="PSYS_SRC_INNERANGLE" type="integer" value="10" status="deprecated">
    <description lang="en">
Deprecated -- Use PSYS_SRC_ANGLE_BEGIN
    </description>
  </constant>

  <constant name="PSYS_SRC_OUTERANGLE" type="integer" value="11" status="deprecated">
    <description lang="en">
Deprecated -- Use PSYS_SRC_ANGLE_END
    </description>
  </constant>

  <constant name="PSYS_SRC_ANGLE_BEGIN" type="integer" value="22"/>
  <constant name="PSYS_SRC_ANGLE_END" type="integer" value="23"/>
  <constant name="PSYS_SRC_BURST_RATE" type="integer" value="13"/>
  <constant name="PSYS_SRC_BURST_PART_COUNT" type="integer" value="15"/>
  <constant name="PSYS_SRC_BURST_RADIUS" type="integer" value="16"/>
  <constant name="PSYS_SRC_BURST_SPEED_MIN" type="integer" value="17"/>
  <constant name="PSYS_SRC_BURST_SPEED_MAX" type="integer" value="18"/>
  <constant name="PSYS_SRC_MAX_AGE" type="integer" value="19"/>
  <constant name="PSYS_SRC_ACCEL" type="integer" value="8"/>
  <constant name="PSYS_SRC_TEXTURE" type="integer" value="12"/>
  <constant name="PSYS_SRC_TARGET_KEY" type="integer" value="20"/>
  <constant name="PSYS_SRC_OMEGA" type="integer" value="21"/>
  <constant name="PSYS_SRC_PATTERN_DROP" type="integer" value="1"/>
  <constant name="PSYS_SRC_PATTERN_EXPLODE" type="integer" value="2"/>
  <constant name="PSYS_SRC_PATTERN_ANGLE" type="integer" value="4"/>
  <constant name="PSYS_SRC_PATTERN_ANGLE_CONE" type="integer" value="8"/>
  <constant name="PSYS_SRC_PATTERN_ANGLE_CONE_EMPTY" type="integer" value="16"/>
  <constant name="PSYS_SRC_OBJ_REL_MASK" type="integer" value="1" status="unimplemented" grid="sl"/>
  <constant name="PSYS_PART_BLEND_FUNC_SOURCE" type="integer" value="24" grid="sl"/>
  <constant name="PSYS_PART_BLEND_FUNC_DEST" type="integer" value="25" grid="sl"/>
  <constant name="PSYS_PART_START_GLOW" type="integer" value="26" grid="sl"/>
  <constant name="PSYS_PART_END_GLOW" type="integer" value="27" grid="sl"/>

  <constant name="OBJECT_UNKNOWN_DETAIL" type="integer" value="-1" version="sl:1.18.3(5)">
    <description lang="en">
Returned by llGetObjectDetails when passed an invalid object parameter type
    </description>
  </constant>

  <constant name="OBJECT_NAME" type="integer" value="1" version="sl:1.18.3(5)">
    <description lang="en">
Used with llGetObjectDetails to get an object's name
    </description>
  </constant>

  <constant name="OBJECT_DESC" type="integer" value="2" version="sl:1.18.3(5)">
    <description lang="en">
Used with llGetObjectDetails to get an object's description
    </description>
  </constant>

  <constant name="OBJECT_POS" type="integer" value="3" version="sl:1.18.3(5)">
    <description lang="en">
Used with llGetObjectDetails to get an object's position
    </description>
  </constant>

  <constant name="OBJECT_ROT" type="integer" value="4" version="sl:1.18.3(5)">
    <description lang="en">
Used with llGetObjectDetails to get an object's rotation
    </description>
  </constant>

  <constant name="OBJECT_VELOCITY" type="integer" value="5" version="sl:1.18.3(5)">
    <description lang="en">
Used with llGetObjectDetails to get an object's velocity
    </description>
  </constant>

  <constant name="OBJECT_OWNER" type="integer" value="6" version="sl:1.18.3(5)">
    <description lang="en">
Used with llGetObjectDetails to get an object's owner's key. Will be NULL_KEY if group owned.
    </description>
  </constant>

  <constant name="OBJECT_GROUP" type="integer" value="7" version="sl:1.18.3(5)">
    <description lang="en">
Used with llGetObjectDetails to get an object's group's key
    </description>
  </constant>

  <constant name="OBJECT_CREATOR" type="integer" value="8" version="sl:1.18.3(5)">
    <description lang="en">
Used with llGetObjectDetails to get an object's creator's key
    </description>
  </constant>

  <constant name="OBJECT_RUNNING_SCRIPT_COUNT" type="integer" value="9">
    <description lang="en">
Used with llGetObjectDetails to get the number of running scripts attached to the object or agent
    </description>
  </constant>

  <constant name="OBJECT_TOTAL_SCRIPT_COUNT" type="integer" value="10">
    <description lang="en">
Used with llGetObjectDetails to get the number of scripts, both running and stopped, attached to the object or agent
    </description>
  </constant>

  <constant name="OBJECT_SCRIPT_MEMORY" type="integer" value="11">
    <description lang="en">
Used with llGetObjectDetails to get the total amount of script memory allocated to the object or agent, in bytes
    </description>
  </constant>

  <constant name="OBJECT_SCRIPT_TIME" type="integer" value="12">
    <description lang="en">
Used with llGetObjectDetails to get the average script CPU time (in seconds) an object/avatar is using
    </description>
  </constant>

  <constant name="OBJECT_PRIM_EQUIVALENCE" type="integer" value="13">
    <description lang="en">
Used with llGetObjectDetails to get the prim equivalence (land impact) of the object
    </description>
  </constant>

  <constant name="OBJECT_PHYSICS_COST" type="integer" value="16">
    <description lang="en">
Used with llGetObjectDetails to get the physics cost
    </description>
  </constant>

  <constant name="OBJECT_SERVER_COST" type="integer" value="14">
    <description lang="en">
Used with llGetObjectDetails to get the server cost
    </description>
  </constant>

  <constant name="OBJECT_STREAMING_COST" type="integer" value="15">
    <description lang="en">
Used with llGetObjectDetails to get the streaming (download) cost
    </description>
  </constant>

  <constant name="OBJECT_CHARACTER_TIME" type="integer" value="17" grid="sl aa">
    <description lang="en">
<!-- TODO: add documentation -->
    </description>
  </constant>

  <constant name="OBJECT_ROOT" type="integer" value="18" grid="sl aa">
    <description lang="en">
<!-- TODO: add documentation -->
    </description>
  </constant>

  <constant name="OBJECT_ATTACHED_POINT" type="integer" value="19" grid="sl aa">
    <description lang="en">
<!-- TODO: add documentation -->
    </description>
  </constant>

  <constant name="OBJECT_PATHFINDING_TYPE" type="integer" value="20" grid="sl aa">
    <description lang="en">
<!-- TODO: add documentation -->
    </description>
  </constant>

  <constant name="OBJECT_RENDER_WEIGHT" type="integer" value="24" grid="sl">
    <description lang="en">
<!-- TODO: add documentation -->
    </description>
  </constant>

  <constant name="OBJECT_HOVER_HEIGHT" type="integer" value="25" grid="sl" version="sl:15.04.08.300724">
    <description lang="en">
<!-- TODO: add documentation -->
    </description>
  </constant>

  <constant name="OBJECT_BODY_SHAPE_TYPE" type="integer" value="26" grid="sl" version="sl:15.04.08.300724">
    <description lang="en">
<!-- TODO: add documentation -->
    </description>
  </constant>

  <constant name="OBJECT_LAST_OWNER_ID" type="integer" value="27" grid="sl" version="sl:15.04.24.301279">
    <description lang="en">
<!-- TODO: add documentation -->
    </description>
  </constant>

  <constant name="OBJECT_CLICK_ACTION" type="integer" value="28" grid="sl" version="sl:15.09.14.305056">
    <description lang="en">
<!-- TODO: add documentation -->
    </description>
  </constant>
